name: 'Run Biome with reviewdog'
description: '🐶 Run Biome with reviewdog on pull requests to improve code review experience.'
author: 'mongolyy'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
    default: '${{ github.token }}'
  workdir:
    description: |
      Working directory relative to the root directory.
      This is where the action will look for a package.json file which declares Biome as a dependency.
      Please note that this is different from the directory where the action will run Biome, which is specified in the biome_flags input.
    required: false
    default: '.'
  ### Flags for reviewdog ###
  tool_name:
    description: 'Tool name to use for reviewdog reporter.'
    required: false
    default: 'Biome'
  level:
    description: 'Report level for reviewdog [info,warning,error].'
    required: false
    default: 'error'
  reporter:
    description: 'Reporter of reviewdog command [github-check,github-pr-review,github-pr-check].'
    required: false
    default: 'github-pr-review'
  filter_mode:
    description: |
      Filtering mode for the reviewdog command [added,diff_context,file,nofilter].
      Default is added.
    required: false
    default: 'added'
  fail_on_error:
    description: |
      Exit code for reviewdog when errors are found [true,false].
      Default is `false`.
    required: false
    default: 'false'
  reviewdog_flags:
    description: 'Additional reviewdog flags.'
    required: false
    default: ''
  ### Flags for Biome ###
  biome_flags:
    description: 'Flags and args for Biome command.'
    required: false
    default: '.'
runs:
  using: 'composite'
  steps:
    - uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: v0.16.0
    - run: $GITHUB_ACTION_PATH/script.sh
      shell: bash
      env:
        # INPUT_<VARIABLE_NAME> is not available in Composite run steps
        # https://github.community/t/input-variable-name-is-not-available-in-composite-run-steps/127611
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_WORKDIR: ${{ inputs.workdir }}
        INPUT_TOOL_NAME: ${{ inputs.tool_name }}
        INPUT_LEVEL: ${{ inputs.level }}
        INPUT_REPORTER: ${{ inputs.reporter }}
        INPUT_FILTER_MODE: ${{ inputs.filter_mode }}
        INPUT_FAIL_ON_ERROR: ${{ inputs.fail_on_error }}
        INPUT_REVIEWDOG_FLAGS: ${{ inputs.reviewdog_flags }}
        INPUT_BIOME_FLAGS: ${{ inputs.biome_flags }}
    - if: ${{ inputs.reporter == 'github-pr-review' && always() }}
      uses: reviewdog/action-suggester@v1
      with:
        github_token: ${{ inputs.github_token }}
        tool_name: ${{ inputs.tool_name }}
        level: ${{ inputs.level }}
        filter_mode: ${{ inputs.filter_mode }}
        fail_on_error: ${{ inputs.fail_on_error }}
        reviewdog_flags: ${{ inputs.reviewdog_flags }}

# Ref: https://haya14busa.github.io/github-action-brandings/
branding:
  icon: 'alert-octagon'
  color: 'blue'
