name: test shell script
on:
  push:
    branches:
      - main
  pull_request:
permissions:
  contents: read

jobs:
  shellspec:
    name: runner / ShellSpec
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: Install latest shellspec
        run: curl -fsSL https://git.io/shellspec | sh -s -- --yes
      - name: Run shellspec
        run: shellspec
